version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build
    steps:
      - checkout
      - run: cd Web && npm install && cd ..
      - run: dotnet build
      - run: cd Web.Tests && dotnet test