version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build
    steps:
      - checkout
      - run: cd Web && npm install && cd ..
      - run: dotnet build
      - run: cd Web.Tests && dotnet test -r output/test-results
      - persist_to_workspace:
        root: output
        paths:
        - test-results
  publish-tests:
    docker:
      - image: microsoft/aspnetcore-build
    steps:
    - attach_workspace:
      at: /temp/output
    - run: echo "Publish tests"

workflows:
  version: 2
  build-n-test:
    jobs:
      - build
      - publish-tests:
          requires:
            - build